import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/style.css'
import Nav from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<Nav />
				{children}
			</body>
		</html>
	)
}
